nijesmik/week01/텀_프로젝트.java

> 2. 틀린 문제 중에 수정 후 merge 하고 싶은 문제는 ✅ task로 작성
> 3. 해당하는 항목이 없을 땐 ❌ 없음으로 작성
> 4. PR 제출 전 🏷️ [**Label**](https://github.com/nijesmik/algo-study-season-2/labels) 꼭 달아주세요!
- 텀 프로젝트
- ❌ 없음
- 보석 도둑
- 구슬 탈출
- 정수 삼각형
- 카카오프렌즈 컬러링북
- ❌ 없음

[week01] nijesmik PR

---

Monami123321/week02/백준_16929_TwoDots.java
Monami123321/week02/백준_17141_연구소2.java
Monami123321/week02/백준_2110_공유기설치.java
Monami123321/week02/프로그래머스_경주로건설.java
Monami123321/week02/프로그래머스_이모티콘할인행사.java

> 2. 틀린 문제 중에 수정 후 merge 하고 싶은 문제는 ✅ task로 작성
> 3. 해당하는 항목이 없을 땐 ❌ 없음으로 작성
> 4. PR 제출 전 🏷️ [**Label**](https://github.com/nijesmik/algo-study-season-2/labels) 꼭 달아주세요!
* 공유기 설치
* 연구소2
* 이모티콘 할인행사
* 경주로 건설
* Two Dots
❌ 없음
❌ 없음
❌ 없음

[week02] Monami123321 PR

---

nijesmik/week02/Two_Dots.java
nijesmik/week02/경주로_건설/Solution.java
nijesmik/week02/공유기_설치.java
nijesmik/week02/연구소_2.java
nijesmik/week02/이모티콘_할인행사/Solution.java

- 공유기 설치
- 연구소 2
- 이모티콘 할인행사
- 경주로 건설
- Two Dots
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week02] nijesmik PR

---

747Socker/week02/TwoDots.java
747Socker/week02/연구소2.java

- Two Dots
다시 해볼게요.
- 이모티콘 할인행사
- 경주로 건설
-  공유기 설치
- ❌ 없음

[week02] 747Socker PR

---

Monami123321/week03/백준_1377_버블소트_카운팅.java
Monami123321/week03/백준_17142_연구소3.java
Monami123321/week03/백준_17143_낚시왕.java
Monami123321/week03/프로그래머스_가장먼노드.java
Monami123321/week03/프로그래머스_단체사진찍기.java

* 낚시왕
* 연구소3
* 가장 먼 노드
* 단체사진 찍기
- 버블 소트 (12%) <br>
1차 : 그냥 버블정렬 만들어보는 문제인 줄 알고, 문제에 주어진 거랑 똑같이 구현했다.
-> <b>시간초과</b>
2차 : 버블정렬이 한 번 돌아갈 때 하나가 정렬된다고 생각해서 연결리스트를 구현해서 삽입-삭제로 만들어봤다.
-> <b><틀림12%></b>
3차 : 질문게시판을 확인해서 손으로 그려보니까 한 번 돌아갈 때 여러 개가 제위치로 찾아갈 수도 있었다!! 바뀐 인덱스를 비교해서 가장 크게 바뀐 값이 정답이었다. -> Arrays.sort -> nlogn
4차 : 너무 느려서 더 빠르게 하는 방법을 생각해보다가 카운팅 정렬 생각이 나서 복습하고 구현해보았다.
- ❌ 없음
- ❌ 없음

[week03] Monami123321 PR

---

nijesmik/week03/가장_먼_노드/Solution.java
nijesmik/week03/낚시왕.java
nijesmik/week03/단체사진_찍기/Solution.java
nijesmik/week03/버블_소트.java
nijesmik/week03/연구소_3.java

- 연구소 3
- 버블 소트
- 낚시왕
- 단체사진 찍기
- 가장 먼 노드
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week03] nijesmik PR

---

damdam6/week03/가장 먼 노드.java
damdam6/week03/단체사진 찍기.java
damdam6/week03/버블소트.java
damdam6/week03/연구소 3.java

- 단체사진 찍기
- 가장 먼 노드
=> 1초 적은 게 아니라 1초 많이 측정 되고 있었음. 연구소 상황을 공동으로 관리하면서 시간은 별개로 다룬 것이 문제가 됨.
=> 소트를 해야 하는 건 동일. 버블 소트의 원리를 제대로 이해하고 있나 확인하는 작업이었음. 버블소트 대신 더 빠른 소트로 해결함!
- 낚시왕
- ❌ 없음

[week03] damdam6 PR

---

747Socker/week03/단체사진찍기.java
747Socker/week03/연구소3.java
747Socker/week03/원자소멸시뮬레이터.java
747Socker/week03/톱니바퀴.java
747Socker/week03/파이프옮기기.java

- 파이프 옮기기
- 연구소 3
- 원자소멸시뮬레이터
- 톱니바퀴
월요일 안에 다시해서 낼게요
- ❌ 
- ❌

[week03] 747Socker PR 

---

KimJihwan98/week03/가장_먼_노드.java
KimJihwan98/week03/낚시왕.java
KimJihwan98/week03/단체사진_찍기.java
KimJihwan98/week03/버블_소트.java
KimJihwan98/week03/연구소3.java

- 연구소3
- 버블소트
- 단체사진 찍기
- 가장 먼 노드
- ❌ 없음
- ❌ 없음

[week03] KimJihwan98 PR

---

damdam6/week03/낚시왕.java
damdam6/week04/당구 연습.java
damdam6/week04/로봇 청소기.java
damdam6/week04/벽 부수고 이동하기 2.java
damdam6/week04/스티커 모으기(2).java
damdam6/week04/트리의 높이와 너비.java

- 스티커 모으기(2)
- 당구 연습
- 로봇 청소기
- 트리의 높이와 너비(시간초과) <br> GPT의 힘을 빌려서 풀었음. 트리를 너무 오랜만에 접해서 구조 짜는 것부터 헤맴. 최적화 시키는데 어려움이 있었음. 후에 여유가 된다면 내 스타일대로 리팩토링 예정.
- 벽 부수고 이동하기 2(메모리/시간초과) <br> 이것도 최적화 하는데 GPT의 도움을 받았음. qu에 삽입하는 조건을 내 스타일대로만 고집하면 안될 것 같음. 효율적인 방안에 대해 고민해 봐야 할 필요성이 요즘 느껴짐.
- ❌ 없음
- 낚시왕

[week04] damdam6 PR

---

nijesmik/week04/당구_연습/Solution.java
nijesmik/week04/로봇_청소기.java
nijesmik/week04/벽_부수고_이동하기_2.java
nijesmik/week04/스티커_모으기_2/Solution.java
nijesmik/week04/트리의_높이와_너비.java

- 트리의 높이와 너비
- 벽 부수고 이동하기 2
- 로봇 청소기
- 당구 연습
- 스티커 모으기(2)
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week04] nijesmik PR

---

Monami123321/week04/백준_14442_벽부수고이동하기2.java
Monami123321/week04/백준_2250_트리의높이와너비.java
Monami123321/week04/백준_4991_로봇청소기.java
Monami123321/week04/프로그래머스_당구연습.java
Monami123321/week04/프로그래머스_스티커모으기2.java

- 트리의 높이와 너비
- 벽 부수고 이동하기 2
- 로봇 청소기
- 당구 연습(0%)
도대체 어떻게 하라는 건지 아이디어 자체가 안 떠올랐다. 360도로 공을 다 날려보라는 건지..
분기를 나눠서 하나하나 처리한다는 글을 읽고 모든 경우의 수를 다 종이에 적어가면서 풀었다.
Math.pow()가 어떤 경우에는 오차가 커져서 틀릴까봐 걱정했는데 통과하긴 했다... 부동소수점 공부를 해봐야겠다.
수학 문제는 너무 어려운 것 같다..
- 스티커 모으기(2)(0%)
DP인 건 알겠는데, 점화식을 도대체 어떻게 짜야 할지 감을 못 잡았다..
첫 번째 스티커를 붙인 경우, 안 붙인 경우로 나눠서 한다는 글을 보고 깜짝 놀랐다.
DP배열에 무엇을 기억할 지 정하는 연습을 해야할 것 같다.
DP는 정말 너무 어렵다..
- ❌ 없음
- ❌ 없음

[week04] Monami123321 PR

---

747Socker/week04/경사로.java
747Socker/week04/당구연습.java
747Socker/week04/벽_부수고_이동하기2.java
747Socker/week04/최단경로.java
747Socker/week04/테트로미노.java

- 당구 연습
- 최단 경로
- 테트로미노
- 경사로
- 벽 부수고 이동하기 2
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week04] 747Socker PR

---

KimJihwan98/week04/당구_연습.java
KimJihwan98/week04/벽_부수고_이동하기2.java
KimJihwan98/week04/스티커_모으기2.java
KimJihwan98/week04/트리의_높이와_너비.java

- 당구_연습
- 스티커_모으기 2
- 트리의_높이와_너비
> 1. 틀린 문제 중에 수정 후 merge 하고 싶은 문제는 ✅ task로 작성 <br> (task는 꼭 **수정 중**이나 **수정 완료 라벨**이 있어야 합니다!)
> 2. 틀린 문제는 몇 퍼센트에서 틀렸는지, 어느 부분이 어려웠는지 함께 작성합니다.
- 로봇_청소기 : 벌금 깔끔하게 내고 다시 도전하겠습니다.
- ❌ 없음

[week04] KimJihwan98 PR

---

nijesmik/week05/경사로.java
nijesmik/week05/놀이_공원.java
nijesmik/week05/보석_쇼핑/Solution.java
nijesmik/week05/열쇠.java
nijesmik/week05/합승_택시_요금/Solution.java

- 경사로
- 열쇠
- 합승 택시 요금
- ❌ 없음
- ❌ 없음

[week05] nijesmik PR

---

Monami123321/week05/백준_14890_경사로.java
Monami123321/week05/백준_1561_놀이공원.java
Monami123321/week05/백준_9328_열쇠.java
Monami123321/week05/프로그래머스_보석쇼핑.java
Monami123321/week05/프로그래머스_합승택시요금.java

- 열쇠
- 경사로
- 합승 택시 요금
- 놀이공원 (0%)
M이 만 개니까, 만 개의 공배수를 구한 다음 시간을 곱해가면서 N보다 커지는지 계산하고, 나머지를 구하고.. 요런식으로 구상했는데 완전 실패했다.. 고민고민하다가 알고리즘 종류를 눌러보니까 이분탐색이었다ㅋㅋ
시간을 기준으로 이분탐색하니까 시간초과 없이 잘 통과됐다. 이분탐색 문제는 이분탐색인지 알아채는 게 참 어려운 것 같다..
- 보석 쇼핑 (효율성 0)
gems를 한 번 돌면서 Map에 <"보석이름" : 갯수> 로  저장해두고, start를 0, end를 gems.length-1로 지정해두었다. map.size()를 보석 갯수로 미리 저장해두고, map.get(gems[start]) 한 값이 1보다 크면 계속 start++ 하고, 반대로 end도 같은 경우 --로 했다. 이렇게 하니까 반은 맞고 반은 틀렸다...
반례를 보니 start end 조정 순서가 잘못된 것 같아서 end를 먼저 땡겨보니 맞았던 게 틀리고 틀렸던 게 맞아서 또 반이었다..
도저히 못 풀겠어서 질문게시판을 보니까 한 번만 훑으면서 O(n)에 푼 코드가 많았다. 포인터 조정의 예술을 본 것 같았다..
- ❌ 없음
- ❌ 없음

[week05] Monami123321 PR

---

747Socker/week05/경사로.java
747Socker/week05/부분합.java
747Socker/week05/소수찾기.java
747Socker/week05/여행가자.java

- 경사로
- 소수찾기
- 여행가자
- 부분합
- ❌ 없음
- 보석 쇼핑
- 합승 택시 요금
- ❌ 없음

[week05] 747Socker PR

---

KimJihwan98/week05/경사로.java
KimJihwan98/week05/놀이공원.java
KimJihwan98/week05/보석_쇼핑.java
KimJihwan98/week05/합승_택시_요금.java

- 경사로
- 놀이공원
- 보석쇼핑
- 합승 택시 요금
- ❌ 없음
- 열쇠
- ❌ 없음

[week05] KimJihwan98 PR

---

Monami123321/week06/백준_11054_가장긴바이토닉부분수열.java
Monami123321/week06/백준_16946_벽부수고이동하기4.java
Monami123321/week06/백준_17822_원판돌리기.java
Monami123321/week06/프로그래머스_도둑질.java
Monami123321/week06/프로그래머스_징검다리건너기.java

- 도둑질
- 징검다리 건너기
- 원판 돌리기
- 가장 긴 바이토닉 부분 수열
- 벽 부수고 이동하기 4
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week06] Monami123321 PR

---

KimJihwan98/week05/경사로.java
KimJihwan98/week05/놀이공원.java
KimJihwan98/week05/보석_쇼핑.java
KimJihwan98/week05/합승_택시_요금.java
KimJihwan98/week06/가장_긴_바이토닉_부분_수열.java
KimJihwan98/week06/도둑질.java
KimJihwan98/week06/벽_부수고_이동하기_4.java
KimJihwan98/week06/원판_돌리기.java
KimJihwan98/week06/징검다리_건너기.java

- 도둑질
- 징검다리_건너기
- 가장_긴_바이토닉_부분_수열 : lis 까먹었어서 dp로 푸는거 다시 공부하고 풀었습니다.
> 1. 틀린 문제 중에 수정 후 merge 하고 싶은 문제는 ✅ task로 작성 <br> (task는 꼭 **수정 중**이나 **수정 완료 라벨**이 있어야 합니다!)
> 2. 틀린 문제는 몇 퍼센트에서 틀렸는지, 어느 부분이 어려웠는지 함께 작성합니다.
- ❌ 없음
- ❌ 없음

[week06] KimJihwan98 PR

---

747Socker/week06/가장긴바이토닉부분수열.java
747Socker/week06/공유기설치.java
747Socker/week06/알파벳.java
747Socker/week06/암호만들기.java
747Socker/week06/줄세우기.java

- 가장 긴 바이토닉 부분 수열
- 줄 세우기
- 공유기 설치
- 알파벳
- 암호만들기
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week06] 747Socker PR 

---

nijesmik/week06/가장_긴_바이토닉_부분_수열.java
nijesmik/week06/도둑질/Solution.java
nijesmik/week06/벽_부수고_이동하기_4.java
nijesmik/week06/원판_돌리기.java
nijesmik/week06/징검다리_건너기/Solution.java

- 벽 부수고 이동하기 4
- 원판 돌리기
- 도둑질
- 가장 긴 바이토닉 부분 수열
- ❌ 없음
- ❌ 없음

[week06] nijesmik PR

---

damdam6/week05/경사로.java
damdam6/week05/놀이 공원.java
damdam6/week05/보석 쇼핑.java
damdam6/week05/열쇠.java
damdam6/week05/합승 택시 요금.java
damdam6/week06/가장 긴 바이토닉 부분 수열.java
damdam6/week06/도둑질.java
damdam6/week06/벽 부수고 이동하기 4.java

- 도둑질
- 벽 부수고 이동하기
- 가장 긴 바이토닉 부분 수열  : 일부 GPT 힘을 빌림. 로직 헷갈리는 부분 참고함!
- 징검다리 건너기
- 원판 돌리기
- 보석 쇼핑
- 합승 택시 요금
- 경사로
- 놀이 공원
- 열쇠

[week06] damdam6 PR

---

Monami123321/week07/백준_1916_최소비용구하기.java
Monami123321/week07/백준_23291_어항정리.java
Monami123321/week07/백준_6593_상범빌딩.java
Monami123321/week07/프로그래머스_광고삽입.java
Monami123321/week07/프로그래머스_입국심사.java

- 최소비용 구하기
- 상범 빌딩
- 어항 정리
- 입국심사
- 광고 삽입 (0%)
HH:MM:SS 형식이라고 해서 자바 DateTimeFormatter라는 클래스가 떠올랐다. 이런 것까지 써야 한다니 하고 충격 받았다.
당연히 아니었고, 그냥 초단위로 환산해서 계산하는 거였다. 프로그래머스 문제 유형에 좀 더 익숙해져야겠다..
문제가 많이 헷갈렸는데, 시청자가 본 영상은 (이상~미만)이었다. 계속 틀리는데 대체 왜 틀리는지 못 찾아서 너무 힘들었다.
문자열 -> 정수형, 구간합 다루기 연습을 할 수 있어서 좋았다.
- ❌ 없음
- ❌ 없음

[week07] Monami123321 PR

---

nijesmik/week06/가장_긴_바이토닉_부분_수열.java
nijesmik/week06/도둑질/Solution.java
nijesmik/week06/벽_부수고_이동하기_4.java
nijesmik/week06/원판_돌리기.java
nijesmik/week06/징검다리_건너기/Solution.java
nijesmik/week07/최소비용_구하기.java

- 최소비용 구하기
- ❌ 없음
- 광고 삽입
- 입국심사
- 어항 정리
- 상범 빌딩
- ❌ 없음

[week07] nijesmik PR

---

KimJihwan98/week07/광고_삽입.java
KimJihwan98/week07/상범_빌딩.java
KimJihwan98/week07/최소비용_구하기.java

- 최소비용_구하기
- 상범_빌딩 : 이거 boolean 체크하는 것 중간에 주석처리한 곳에서 하면 왜 메모리 초과인지 알고싶어요.
- 광고_삽입 : 누적합 생각하기가 너무 어려웠습니다.. 그리고 long 타입 낚시인거 너무 열받습니다.
- ❌ 없음
- 입국_심사
- 어항_정리 : 다음주까지풀겠습니다 
- ❌ 없음

[week07] KimJihwan98 PR

---

nijesmik/week07/상범_빌딩.java
nijesmik/week08/강의실_배정.java
nijesmik/week08/레벨_햄버거.java
nijesmik/week08/용액_합성하기.java
nijesmik/week08/톱니바퀴_2.java

- 강의실 배정
- 레벨 햄버거
- 용액 합성하기
- 톱니바퀴 (2)
- ❌ 없음
- ❌ 없음
- 상범 빌딩

[week08] nijesmik PR

---

Monami123321/week08/백준_11000_강의실배정.java
Monami123321/week08/백준_14921_용액합성하기.java
Monami123321/week08/백준_15662_톱니바퀴2.java
Monami123321/week08/백준_16974_레벨햄버거.java

- 강의실 배정
- 톱니바퀴 (2)
- 용액 합성하기
- 레벨 햄버거 (0%)
전체 갯수, 패티 갯수까지는 구했는데 X층까지 먹는 걸 어떻게 처리해야 될 지 감을 못 잡았다.
재귀적으로 푸는 답을 확인하고 다시 풀었다. 어떻게 이런 방법을 바로 생각해내는지 참 신기하다.
- ❌ 없음
- ❌ 없음

[week08] Monami123321 PR

---

747Socker/week08/강의실배정.java
747Socker/week08/용액_합성하기.java
747Socker/week08/톱니바퀴2.java

- 강의실 배정
- 톱니바퀴 2
- 용액 합성하기
- ❌ 없음
- 레벨 햄버거
- ❌ 없음

[week08] 747Socker PR

---

damdam6/week08/Baek11000.java
damdam6/week08/Baek15662.java
damdam6/week08/Baek16974.java

- 레벨 햄버거
- 톱니바퀴 (2)
- 강의실 배정
- 용액 합성하기
- ❌ 없음

[week08] damdam6 PR

---

Monami123321/week09/백준_17144_미세먼지_안녕.java
Monami123321/week09/백준_1790_수이어쓰기2.java
Monami123321/week09/프로그래머스_도넛과막대그래프.java
Monami123321/week09/프로그래머스_표편집.java

- 표 편집
- 미세먼지 안녕!
- 수 이어 쓰기 2
- 도넛과 막대 그래프
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week09] Monami123321 PR

---

KimJihwan98/week09/도넛과_막대_그래프.java
KimJihwan98/week09/미세먼지_안녕.java
KimJihwan98/week09/수_이어_쓰기2.java
KimJihwan98/week09/표_편집.java

- 표_편집
- 도넛과_막대_그래프 <br> 그래프 문제인척하는 꼼수로 풀어라 하는 문제인듯.. 규칙찾는 것이 재밌었습니다. node개수 안나온게 힌트였던 것 같기도 합니다.
> 1. 틀린 문제 중에 수정 후 merge 하고 싶은 문제는 ✅ task로 작성 <br> (task는 꼭 **수정 중**이나 **수정 완료 라벨**이 있어야 합니다!)
> 2. 틀린 문제는 몇 퍼센트에서 틀렸는지, 어느 부분이 어려웠는지 함께 작성합니다.
- ❌ 없음
- ❌ 없음

[week09] KimJihwan98 PR

---

747Socker/week09/도넛과막대그래프.java
747Socker/week09/미세먼지_안녕.java
747Socker/week09/수_이어_쓰기2.java
747Socker/week09/표편집.java

- 미세먼지 안녕
- 수 이어 쓰기2 <br> 5분만에 풀고..... 너무 잘풀려서 잘 못풀었다는 것을 인지했습니다.... 필요한 수만 뽑게 생각해도  메모리초과 시간초과에 시달리다 인터넷 참고해서 버퍼나 빌더 등등을 썼습니다
- 표 편집(79%) <br> 효율성에서 시간초과가 발생했습니다. 이유를 알 듯 한데(노드를 정의해서 풀어야 할듯)... 다시 풀어 보겠습니다. 일단 그냥 제출 하렵니다..
- 도넛과 막대 그래프 <br> dfs로 해도 맞긴하나 봅니다.. 시도 조차 안하긴 했는데 인터넷에서 파이썬 정답 코드 슥 보고 거의 그대로 카피해버림.... 답을 확인해버려서 이미 늦었다랄까요... 그래도 map 다룰 때 putIfAbsent라는 새로운 메서드를 공부했습니다. putIfAbsent란 키가 이미 존재할 땐 null인 그런 메서드라고 하네요.
- ❌ 없음
- ❌ 없음

[week09] 747Socker PR 

---

damdam6/week09/도넛과 막대 그래프.java
damdam6/week09/미세먼지 안녕.java
damdam6/week09/수 이어 쓰기 2.java
damdam6/week09/표 편집.java

-> 고침. 방향에 문제가 있었던듯
- > 감이 안와서 GPT 도움 받았음. stack이용하고 LinkedList의 특징을 잘 활용해야 되는 문제였음.
- ❌ 없음
- ❌ 없음

[week09] damdam6 PR

---

Monami123321/week10/백준_14499_주사위굴리기.java
Monami123321/week10/백준_1744_수묶기.java
Monami123321/week10/프로그래머스_베스트앨범.java
Monami123321/week10/프로그래머스_산모양타일링.java

- 수 묶기
- 베스트앨범
- 주사위 굴리기
- 산 모양 타일링(0%)
주어진 모든 삼각형 갯수를 k라고 할 때
삼각형으로 다 채우거나, 마름모를 하나 넣거나 두개 넣거나.... K개 넣거나
tops를 돌면서 1인 경우 k++ 해서 숫자를 확정하고 kC1 + kC2 + kC3 + ... + kCk 이렇게 하는데
nCr=  n-1Cr-1 + n-1Cr 을 이용해서 재귀로 구하는데 값을 DP에 저장하면서 풀어보려고 했다.
당연히 실패했다. 카카오 해설을 보고 풀었다...
- ❌ 없음
- ❌ 없음

[week10] Monami123321 PR

---

week10/베스트앨범/Solution.java
week10/산_모양_타일링/Solution.java
week10/수_묶기.java
week10/주사위_굴리기.java

- 수 묶기
- 산 모양 타일링
- 주사위 굴리기
- 베스트앨범
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week10] nijesmik PR

---

747Socker/week10/산모양타일링.java
747Socker/week10/수묶기.java

- 수묶기 <br> 음수와 양수를 배열에 담고 경계인 0, 1 처리
> 1. 틀린 문제 중에 수정 후 merge 하고 싶은 문제는 ✅ task로 작성 <br> (task는 꼭 **수정 중**이나 **수정 완료 라벨**이 있어야 합니다!)
> 2. 틀린 문제는 몇 퍼센트에서 틀렸는지, 어느 부분이 어려웠는지 함께 작성합니다.
- 산모양 타일링 <br> 30분 정도 고민 해보다가 답지를 시원하게 보고 카피했습니다... 무슨 말인지는 알겠는데 여전히 첨부터 풀 수 있을까 하는 의문과 함께 납득은 안됩니다..........
- ❌ 없음
- ❌ 없음

[week10] 747Socker PR 

---

damdam6/week10/베스트앨범.java
damdam6/week10/산 모양 타일링.java
damdam6/week10/수 묶기.java
damdam6/week10/주사위 굴리기.java

- 산 모양 타일링
- 수 묶기
- 베스트앨범 <br> Map관련 메서드들 공부하고 싶어서 찾아보고 클론코딩식으로 작업함. 일부는 GPT코드 분석을 통해서 공부함.
- 주사위 굴리기 (0%) <br> 주사위 배열을 int[6]로 만들었을 때 천장을 향하는 면과 바닥을 향하는 면이 잘 연결되지 않는 것 같음. 배열 구조에 대해서 다시 생각해봐야함.
- ❌ 없음
- ❌ 없음

[week10] damdam6 PR

---

nijesmik/week11/리모컨.java
nijesmik/week11/야구.java
nijesmik/week11/양과_늑대/Solution.java

- 양과 늑대
- 리모컨
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week11] nijesmik PR

---

Monami123321/week11/백준_1107_리모컨.java
Monami123321/week11/백준_17281_야구.java
Monami123321/week11/프로그래머스_셔틀버스.java
Monami123321/week11/프로그래머스_양과늑대.java

- ⚾
- 셔틀버스
- 리모컨
- 양과 늑대 (83%)
루트 노드에서 bfs 시작 -> 도달할 수 있는 모든 양 pq에 넣기 -> 우선순위는 1) 양-늑대가 큰 순 2) 같으면 형제들 다 봤을 때 양이 많은 순 -> 골랐으면 루트노드까지 거꾸로 돌아가면서 타입을 -1로 바꿔서 양도 늑대도 아니게 하기
이걸 양 숫자만큼 반복하고 골라진 양 숫자를 리턴했다!
테스트 케이스 3개가 자꾸 틀려서 오래 고민했는데 결국 해결하지 못했다.
생각해보니 양 - 늑대가 더 작아도 그 밑에 양이 완전 많으면 그쪽을 먼저 갔어야 하는데,
pq 정렬 기준을 dfs 돌려서 해야하나 ? 구현을 못했다 ..
카카오 해설을 보고 dfs로 다시 풀었다.. 테트로미노랑 비슷한 문제였는데 전혀 떠올리지 못했다. 반성
- ❌ 없음
- ❌ 없음

[week11] Monami123321 PR

---

KimJihwan98/week11/리모컨.java
KimJihwan98/week11/양과_늑대.java

[week11] KimJihwan98 PR

---

747Socker/week11/리모컨.java
747Socker/week11/양과늑대.java

- 리모컨
- 양과 늑대(16%) <br> 처음부터 단순하게 bfs로 풀기 시작했는데 틀렸네요.. 고집부리면서 그냥 푸는데 안되네여 체크하고 돌아가서 다시 체크나 가지치기 하려면 dfs로 해야 할 듯 합니다
- ❌ 없음
- ❌ 없음

[week11] 747Socker PR

---

hunteac/week12/불.java
hunteac/week12/아이템_줍기.java
hunteac/week12/캐슬_디펜스.java
hunteac/week12/표현_가능한_이진트리.java

- 불
- 표현 가능한 이진트리
- 캐슬 디펜스
- 아이템 줍기
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week12] hunteac PR

---

Monami123321/week12/백준_17135_캐슬디펜스.java
Monami123321/week12/백준_4179_불.java
Monami123321/week12/프로그래머스_아이템줍기.java
Monami123321/week12/프로그래머스_표현가능한이진트리.java

-불
-캐슬 디펜스
- 표현 가능한 이진트리(0%)
어떻게 해야 될지 감도 못 잡았고 오래 고민했는데 아이디어도 안 떠올랐다.. 블로그 검색해봤는데 답을 봐도 첨에 이해를 못했다... 몇 번 베껴쓰고 다시 풀고 했다.. 진짜 우울해지는 문제였다. 그래도 메서드 몇 개 배울 수 있어서 좋았다.
- 아이템 줍기 (0%)
그냥 사각형을 1로 덮어버리고 바깥을 bfs 돌려서 테두리를 그었는데, 사각형이 딱 붙어있으면 제대로 안 그어졌다. 어떻게 해결하지 고민하다가 결국 못했고, 답지를 보니까 크기를 2배로 늘리는 방법이 있었다.. 
- ❌ 없음
- ❌ 없음

[week12] Monami123321 PR 

---

KimJihwan98/week12/베스트앨범.java
KimJihwan98/week12/불.java
KimJihwan98/week12/산_모양_타일링.java
KimJihwan98/week12/아이템_줍기.java
KimJihwan98/week12/주사위_굴리기.java
KimJihwan98/week12/캐슬_디펜스.java
KimJihwan98/week12/표현_가능한_이진트리.java

- 캐슬_디펜스 : 생각보다 너무 까다로웠다. pq, set, queue 세개 써서 메모리가 너무 큰데 다들 어떻게풀었는지 궁금합니다.
- 표현_가능한_이진트리 : 몇층인지 또 양쪽으로 나눌때 인덱스 관리가 어려웠다.
- 불! : 생각보다 까다롭다..
- 아이템_줍기 : 맵을 두배로 늘리는걸 생각못해서 구글링을 했다..
- ❌ 없음
- 베스트앨범(10주차)
- 산_모양_타일링(10주차)
- 주사위_굴리기(10주차)

[week12] KimJihwan98 PR

---

747Socker/week10/베스트앨범.java
747Socker/week10/주사위굴리기.java
747Socker/week12/불.java
747Socker/week12/아이템줍기.java
747Socker/week12/캐슬디펜스.java
747Socker/week12/표현가능한이진트리.java

- 불
- 캐슬 디펜스 <br> 접근할 때 node 클래스로 관리해야 했어야 했는데 그러지 않아도 된다고 생각해서(m열 당 궁수 하나) 애먹었습니다. 결국 놓친 부분을 모르겠어서 gpt한테 계속 고쳐 달라고 했습니다.
- 표현 가능한 이진트리 <br> dfs로 탐색하는 것까지 생각하고 고민해 봤는데.. 문제의 조건들을 어떻게 처리할지 너무 어려웠습니다. 답지 하나 보고 열심히 베꼈는데... 아직 잘 모르겠어요 특히 트리 문제를 많이 안풀어봐서 트리 접근도 어색하고 어렵네요
- 아이텝 줍기(59%) <br> 겹친 부분을 제대로 처리 못해서 틀림!
- ❌ 없음
- 주사위_굴리기
- 베스트앨범

[week12] 747Socker PR

---

damdam6/week11/[1차] 셔틀버스.txt
damdam6/week11/야구공.txt
damdam6/week12/불!.txt
damdam6/week12/표현 가능한 이진트리.txt

- 불!
- ❌ 없음
- [1차] 셔틀버스 <br> 셔틀버스 시간을 분으로 바꾸는 접근법은 GPT에서 힌트를 얻음.
- ⚾

[week12] damdam6 PR

---

hunteac/week13/세_수의_합.java
hunteac/week13/자물쇠와_열쇠.java
hunteac/week13/테트로미노.java
hunteac/week13/파괴되지_않은_건물.java

- 테트로미노
- 자물쇠와 열쇠
- 세 수의 합
- 파괴되지 않은 건물
: 완전탐색을 진행할 경우 시간초과가 발생하여 고민했지만 누적합을 구한다는 접근 자체를 하지 못했다. 
- ❌ 없음
- ❌ 없음

[week13] hunteac PR

---

KimJihwan98/week13/세_수의_합.java
KimJihwan98/week13/자물쇠와_열쇠.java
KimJihwan98/week13/테트로미노.java
KimJihwan98/week13/파괴되지_않은_건물.java

- 자물쇠와_열쇠
- 테트로미노
- 세 수의 합(시간초과) : 시간초과를 해결하지 못해서 답지를 참고했는데 이항해서 하는 방식은 생각못했네요 ㅠ
- 파괴되지 않은 건물(효율성 0%) : 이거는 진짜 답지를 보지않고서는 효율성을 통과하기 너무 어려워요. 누적합도 어려운데 누적합을 이차원배열로 확장시켜서 생각하는게 쉽지 않네요.
<!-- '틀린 문제' 작성 방법
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week13] KimJihwan98 PR

---

nijesmik/week13/세_수의_합.java
nijesmik/week13/자물쇠와_열쇠/Solution.java
nijesmik/week13/테트로미노.java
nijesmik/week13/파괴되지_않은_건물/Solution.java

- 자물쇠와 열쇠
- 테트로미노
- 세 수의 합
- 파괴되지 않은 건물
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week13] nijesmik PR

---

Monami123321/week13/백준_14500_테트로미노.java
Monami123321/week13/백준_2295_세수의합.java
Monami123321/week13/프로그래머스_자물쇠와열쇠.java
Monami123321/week13/프로그래머스_파괴되지않은건물.java

- ❌ 없음
-  테트로미노(0%)
풀었던 건데도 헤맸다.. 방문처리에서 실수했다 ㅜㅜ 특이하게 처리하는 dfs를 더 연습해야겠다.
- 자물쇠와 열쇠(0%)
오래 고민했는데 어떻게 구현할지 전혀 아이디어 안 떠올랐다. 힌트 보고 배열 돌려가면서 꾸역꾸역 했는데 너무 이상하다.. 더 효과적으로 깨끗하게 짜보고 싶다.
- 세 수의 합(0%)
a + b + c 가 될 수 있는 모든 경우의 수를 배열로 저장해놓고 n개의 수를 이분탐색하면서 K가 있는지 찾아보려고 했다.
배열원소가 1000 * 1000 * 1000  라서 메모리 초과가 났다. 고민하다가 못 풀고 답지를 봤다. a + b = k - c 로 줄이는 방법이 있었다. O(n * log(n^3)) -> O(n^2 * log(n^2)) 인데 메모리는 훨씬 덜 쓰게 해서 신기했다.
- 파괴되지 않은 건물(효율성 0%)
효율성 손도 못 댔다. 카카오 공식 해설을 보고 풀었다. 이런 방법이 있다니~
- ❌ 없음
- ❌ 없음

[week13] Monami123321 PR 

---

747Socker/week13/세수의합.java
747Socker/week13/자물쇠와열쇠.java
747Socker/week13/테트로미노.java
747Socker/week13/파괴되지않은건물.java

- 테트로미노
- 세수의 합(메모리 초과) <br> 모두 계산하는 방식이라 틀림
- 파괴되지 않은 건물(사실상 0%) <br> 누적합이란걸 알고 시도해서 접근은 가능했으나 사실상 못풀었다
- ❌ 없음
- ❌ 없음

[week13] 747Socker PR

---

damdam6/week13/세 수의 합.java
damdam6/week13/자물쇠와 열쇠.java
damdam6/week13/테트로미노.java
damdam6/week13/파괴되지 않은 건물.java

- 자물쇠와 열쇠
- 테트로미노 (0%) <br> dfs로 되지 않는 'ㅗ' 예외 생각해내기 어려워서 해답 참고
- 세 수의 합(0%) <br> 이분탐색이라는 키워드를 보고 범위 내 숫자를 전부 이분탐색 하려다 실패. 이분탐색이 중요한 키워드가 아니었다는 걸 해답을 보고 깨달음. (속았다.) 기왕 연습하는 김에 Collections 명령어들 참고하여 활용해봄. 기억 더듬기.
- 파괴되지 않은 건물(효율성 실패) <br> 행렬 for문 대상을 바꿔가면서 실험해보았으나 복잡도 떨어트리는데 실패. 누적합 접근을 해답 참조하여 알아냄. 누적합 신기했다.
- ❌ 없음
- ❌ 없음

[week13] damdam6 PR

---

KimJihwan98/week14/A와_B.java
KimJihwan98/week14/드래곤_커브.java
KimJihwan98/week14/미로_탈출_명령어.java
KimJihwan98/week14/추석_트래픽.java

- 드래곤_커브
- A와_B : 비트마스킹으로는 못푸나요?
- 미로_탈출_명령어(35%) : 카카오라서 그냥 dfs말고 신박하게 풀고싶어서 도전했는데 그냥 dfs였어요 ㅠㅠ
- 추석_트래픽(45%) : 접근 방식을 생각 못해서 답지 참고했어요 
- ❌ 없음
- ❌ 없음

[week14] KimJihwan98 PR

---

hunteac/week14/A와_B.java
hunteac/week14/드래곤_커브.java
hunteac/week14/미로_탈출_명령어.java
hunteac/week14/추석_트래픽.java

- 드래곤 커브
- 미로 탈출 명령어
- A와 B
- 추석 트래픽
1. 30%, 시, 분, 초를 각각 어떻게 계산해야할지 고민했는데 모두 초로 변환하고 계산을 하는 방법을 습득했다.
- ❌ 없음
- ❌ 없음

[week14] hunteac PR

---

Monami123321/week14/백준_12904_A와B.java
Monami123321/week14/백준_15685_드래곤커브.java
Monami123321/week14/프로그래머스_미로탈출명령어.java
Monami123321/week14/프로그래머스_추석트래픽.java

- 드래곤 커브
- A와 B
- 미로 탈출 명령어(시간초과 5%)
*우선순위대로 dfs 할 것 *백트래킹 생각을 못했다.. 
답지 보고 푸는 비중이 점점 늘어나고 있다..
- 추석 트래픽(0%)
1000 * 1000 이라 다 돌려봐도 되는데, 시간이 터질 것 같다는 생각에 N에 풀 수 없나 계속 고민하다가 실패했다..
오타를 너무 많이 내서 디버깅 하는 데 오래걸렸다.
- ❌ 없음
- ❌ 없음

[week14] Monami123321 PR

---

747Socker/week14/A와B.java
747Socker/week14/드래곤커브.java
747Socker/week14/미로_탈출_명령어.py
747Socker/week14/추석트래픽.java

- A와 B
- 드래곤커브
- 미로 탈출 명령어(30%)  <br> 임파서블 조건, 가지치기 조건 등 놓치는게 많았습니다. 답지 보고 대폭 수정...
- 추석 트래픽(0%) <br> 힘들어서 답지 봤습니다. format으로 푸는 신박한 방식을 배웠습니다
- ❌ 없음
- ❌ 없음

[week14] 747Socker PR

---

nijesmik/week14/A와_B.java
nijesmik/week14/드래곤_커브.java
nijesmik/week14/미로_탈출_명령어/Solution.java
nijesmik/week14/추석_트래픽/Solution.java

- 미로 탈출 명령어
- A와 B
- 드래곤 커브
- 추석 트래픽
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week14] nijesmik PR

---

damdam6/week14/A와 B.java
damdam6/week14/드래곤 커브.java
damdam6/week14/미로 탈출 명령어.txt
damdam6/week14/추석 트래픽.java

- 드래곤 커브
- A와 B(2%) <br> 범위 지정이 달라지는 인덱스값for문은 주의해야된다. 단순히 abs로 풀려고 해서 헤맸다. 그래도 스스로 풀었음. 굿.
- ❌ 없음
- ❌ 없음

[week14] damdam6 PR

---

hunteac/week15/다리_만들기.java
hunteac/week15/보행자_천국.java
hunteac/week15/이차원_동전_뒤집기.java
hunteac/week15/이차원_배열과_연산.java

- 보행자 천국
- 이차원 배열과 연산
- 다리 만들기
- 2차원 동전 뒤집기
- 0%, 브루트포스 문제인줄 알았지만 시간초과가 계속 발생했다. 하지만 행의 변화만 체크해도 풀 수 있는 문제였다.
- ❌ 없음
- ❌ 없음

[week15] hunteac PR

---

Monami123321/week15/백준_17140_이차원배열과연산.java
Monami123321/week15/백준_2146_다리만들기.java
Monami123321/week15/프로그래머스_2차원동전뒤집기.java
Monami123321/week15/프로그래머스_보행자천국.java

- 다리 만들기
- 2차원 동전 뒤집기
- 이차원 배열과 연산
메서드로 뺄 생각을 안하고 막 구현하다가 디버깅하는 데 엄청나게 오래 걸렸다..
- 보행자 천국(0%)
int[m][n] 으로 해보려고 했는데 잘 안됐다;; 위에서 오거나 왼쪽에서 왔는데 2면 다시 위를 보고 왼쪽을 보고..
어떻게 구현하지 하다가 실패했다. 3차원 배열로 왼쪽 위쪽을 아예 따로 기록하는 방법이 있길래 그렇게 풀었다.
- ❌ 없음
- ❌ 없음

[week15] Monami123321 PR

---

KimJihwan98/week15/다리_만들기.java
KimJihwan98/week15/보행자_천국.java
KimJihwan98/week15/이차원_동전_뒤집기.java
KimJihwan98/week15/이차원_배열과_연산.java

- 이차원_배열과_연산 : 처음 r,c 예외처리 안해줘서 시간낭비했던 문제였어요.
- 보행자_천국 : 3단계중에 가장 쉬웠던..
- 다리_만들기
- ❌ 없음
- ❌ 없음

[week15] KimJihwan98 PR

---

747Socker/week15/보행자천국.java
747Socker/week15/이차원배열과연산.java

- 이차원 배열과 연산
- 보행자 천국 <br> 조건을 잘못 걸었어요
- ❌ 없음
- ❌ 없음

[week15] 747Socker PR

---

damdam6/week15/보행자 천국.java
damdam6/week15/이차원 배열과 연산.java

- 보행자 천국
- 다리 만들기
- 2차원 동전 뒤집기
- ❌ 없음

[week15] damdam6 PR

---

nijesmik/week16/자동차_테스트/Main.java
nijesmik/week16/타일_채우기.java

- 자동차 테스트
- 타일 채우기
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week16] nijesmik PR

---

KimJihwan98/week15/다리_만들기.java
KimJihwan98/week15/보행자_천국.java
KimJihwan98/week15/이차원_동전_뒤집기.java
KimJihwan98/week15/이차원_배열과_연산.java
KimJihwan98/week16/사다리_조작.java
KimJihwan98/week16/순서대로_방문하기.java
KimJihwan98/week16/자동차_테스트.java
KimJihwan98/week16/타일_채우기.java

- 타일_채우기
- 자동차_테스트
- 순서대로_방문하기
- ❌ 없음
- ❌ 없음

[week16] KimJihwan98 PR

---

Monami123321/week16/백준_15684_사다리조작.java
Monami123321/week16/백준_2133_타일채우기.java
Monami123321/week16/소프티어_순서대로방문하기.java
Monami123321/week16/소프티어_자동차테스트.java

- 자동차 테스트
- 순서대로 방문하기
- 사다리 조작
사다리를 놓을 수 있는 모든 경우의 수를 구하고 0 1 2 3 개 놨을 때를 모두 돌려서 불가능하면 -1이 나오게 했다.
사다리 놓는걸 boolean으로 했다가 왼쪽갈때 오른쪽갈때 구별을 못하는 걸 발견 못했다.. 엄청 고생했다
다른 정답 코드보다 훨씬 느린데 더 좋은 방법이 있는지 모르겠다.
- 타일채우기(0%)
예외모양 도저히 생각을 못했다 +2씩 올라감
- ❌ 없음

[week16] Monami123321 PR

---

747Socker/week16/DSLR.java
747Socker/week16/스타트와링크.java
747Socker/week16/자동차테스트.java
747Socker/week16/타일채우기.java

- 자동차테스트 <br> 무작정 브루트포스 하려고 하지 말아야겠다.
- 스타트와링크
- DSLR
- 타일채우기(0%) <br> 참고 없이 힘듦
- ❌ 없음
- ❌ 없음

[week16] 747Socker PR

---

hunteac/week16/순서대로_방문하기.java
hunteac/week16/자동차_테스트.java
hunteac/week16/타일_채우기.java

- 자동차 테스트
- 타일 채우기
- 순서대로 방문하기
- 사다리 조작
- 0%, 시도해봤는데 시간이 너무 오래걸릴 것 같아서 포기,,, 면접 준비했어요 
- ❌ 없음
- ❌ 없음

[week16] hunteac PR

---

nijesmik/week16/사다리_조작.java
nijesmik/week16/순서대로_방문하기/Main.java
nijesmik/week17/IPv_6.java
nijesmik/week17/등굣길/Solution.java
nijesmik/week17/종이_조각.java
nijesmik/week17/출퇴근길/Main.java

- IPv6
- 출퇴근길
- 종이 조각
- 등굣길
- ❌ 없음
- ❌ 없음
- 순서대로 방문하기
- 사다리 조작

[week17] nijesmik PR

---

KimJihwan98/week17/IPv6.java
KimJihwan98/week17/등굣길.java
KimJihwan98/week17/종이_조각.java
KimJihwan98/week17/출퇴근길.java

- IPv6
- 등굣길
- 출퇴근길 : 역방향 생각못해서 답 참고해서 풀었습니당
-  [x] 종이조각 :  dfs인거같은데 비트마스킹 답지 참고해서 다시풀어보겠습니다.. -> 그냥 완탐 dfs로 풀었습니다.
- ❌ 없음
- ❌ 없음

[week17] KimJihwan98 PR

---

Monami123321/week17/백준_14391_종이조각.java
Monami123321/week17/백준_3107_IPv6.java
Monami123321/week17/소프티어_출퇴근길.java
Monami123321/week17/프로그래머스_등굣길.java

- IPv6
- 등굣길
- 출퇴근길(0%)
해설을 보고 풀었습니다.. 역방향 인접리스트에 대해서 배웠다!
- 종이 조각(0%)
완전탐색인지 전혀 몰랐다. 비트마스킹이라는 힌트를 확인했는데, 어떻게 비트마스킹인지 모르겠어서 도전도 못했다.
결국 해설을 보고 DFS로 풀었는데, 방문처리를 잘못해서 한참 걸렸다. 가로 -> 세로, 세로 -> 가로 에서 막힐 수 있는 걸 생각 못했다.
- ❌ 없음
- ❌ 없음

[week17] Monami123321 PR

---

747Socker/week17/IPv6.py
747Socker/week17/알파벳.java

- IPv6
- 알파벳
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week17] 747Socker PR

---

hunteac/week17/IPv6.java
hunteac/week17/등굣길.java
hunteac/week17/종이_조각.java
hunteac/week17/출퇴근길.java

- IPv6
- 출퇴근길
- 등굣길
- 종이 조각
부르트포스인건 알았지만 비트마스킹을 활용한 방법을 생각이 나지 않아 해설을 참고했습니다. 비트마스킹을 제대로 공부했다!
- ❌ 없음
- ❌ 없음

[week17] hunteac PR

---

KimJihwan98/week18/공주님의_정원.java
KimJihwan98/week18/인싸들의_가위바위보.java
KimJihwan98/week18/직사각형_탈출.java
KimJihwan98/week18/합이_0.java

- 직사각형_탈출
- 공주님의_정원
- 인싸들의_가위바위보
- 합이_0
- ❌ 없음
- ❌ 없음

[week18] KimJihwan98 PR

---

nijesmik/week18/공주님의_정원.java
nijesmik/week18/직사각형_탈출/Main.java

- 직사각형 탈출
- 공주님의 정원
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week18] nijesmik PR

---

Monami123321/week18/백준_16973_직사각형탈출.java
Monami123321/week18/백준_16986_인싸들의가위바위보.java
Monami123321/week18/백준_2457_공주님의정원.java
Monami123321/week18/백준_3151_합이0.java

- 직사각형 탈출
- 공주님의 정원
- 인싸들의 가위바위보
- 합이 0
- ❌ 없음
- ❌ 없음
- ❌ 없음

[week18] Monami123321 PR

---

747Socker/week18/공주님의정원.java
747Socker/week18/인싸가위바위보.java
747Socker/week18/직사각형탈출.java
747Socker/week18/합이0.java

- 직사각형 탈출
- 합이 0
- 인싸들의 가위바위보 <br> 인덱스 관리가 힘들었어요 참고했어요
- 공주님의 정원(100%) <br> 답지 보고 숫자 변환하고... 풀었어요
- ❌ 없음
- ❌ 없음

[week18] 747Socker PR
